In [19]:
import pandas as pd
data_from_baza = pd.read_csv('report.csv', delimiter=',')
data_from_baza

MIP      STDIP      EKIP       SIP         MC       STDC  \
0      137.218750  45.390655  0.034985  0.134409   3.204013  17.177857   
1       93.773438  41.883062  0.371402  1.291232   1.482441  12.959050   
2       73.632812  35.461218  1.153607  4.161082   2.099498  13.057474   
3       93.429688  39.883166  0.602060  1.518548   2.475753  14.146578   
4      131.625000  44.111896  0.108905  0.239879  33.888796  70.398342   
...           ...        ...       ...       ...        ...        ...   
17893  121.117188  50.127279 -0.017936 -0.193900   1.566890  10.804730   
17894  120.679688  40.918542  0.291465  0.627087   1.473244  13.912476   
17895  138.101562  47.935314 -0.181827 -0.283746   3.270903  16.963817   
17896  119.523438  44.198410  0.026662  0.352641   1.828595  12.674068   
17897  154.875000  48.590766 -0.285643  0.129281   4.153010  21.971915   

             EKC          SC  TARGET  
0       7.494588   74.003104       0  
1      12.242911  180.158844       0  
2      10.013591  140.894151       0  
3       8.770640  107.970173       0  
4       1.689460    1.031847       0  
...          ...         ...     ...  
17893  13.737064  269.096109       0  
17894  13.144044  203.416941       0  
17895   6.988850   63.043499       0  
17896  11.153939  166.582439       0  
17897   6.746838   52.230021       0  

[17898 rows x 9 columns]

In [20]:
train_data = data_from_baza[((data_from_baza['TARGET'] == 0) & (data_from_baza['MIP'] >= 94.6640625 ) & (data_from_baza['MIP'] <= 95.2890625)) | ((data_from_baza['TARGET'] == 1) & (data_from_baza['MIP'] >= 52.9296875) & (data_from_baza['MIP'] <= 58.7890625))]
train_data.sort_values(by=['MIP'], inplace=True)
train_data = train_data.reset_index()
train_data

/tmp/ipykernel_4826/661615659.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data.sort_values(by=['MIP'], inplace=True)


index        MIP      STDIP      EKIP        SIP          MC       STDC  \
0     9498  52.929688  50.551673  2.581866   6.350838  115.790970  70.361297   
1     3564  52.968750  31.446367  3.410426  16.839254   41.168896  67.290303   
2     8016  53.023438  39.592744  2.589680   8.870819    9.274247  36.469395   
3     5530  53.273438  32.414000  3.773294  17.974038   44.418060  74.494186   
4    10376  53.289062  37.334877  3.650844  16.009453   33.414716  62.538351   
..     ...        ...        ...       ...        ...         ...        ...   
197  12604  95.257812  47.905383  0.521461  -0.066145    4.427258  24.166553   
198   1109  95.265625  45.770399  0.524977   0.841960    2.593645  19.597849   
199   8423  95.281250  38.005743  0.680265   2.195606    2.143813  17.323049   
200  10681  95.289062  42.485136  0.427858   0.884141    4.054348  26.314179   
201    974  95.289062  47.040068  0.411826   0.503116    4.890468  23.738871   

           EKC          SC  TARGET  
0     0.138440   -0.547593       1  
1     1.648880    1.635625       1  
2     4.777220   24.128061       1  
3     1.570768    1.119030       1  
4     1.997741    3.013135       1  
..         ...         ...     ...  
197   6.582779   47.425836       0  
198   8.765388   82.610265       0  
199  10.224654  116.802729       0  
200   6.933278   48.946050       0  
201   6.239236   44.177220       0  

[202 rows x 10 columns]

In [21]:
train_data.mean()

index     8401.331683
MIP         75.484066
STDIP       40.174439
EKIP         1.711331
SIP          6.573146
MC          22.833289
STDC        39.135336
EKC          6.139907
SC          70.318882
TARGET       0.500000
dtype: float64

In [22]:
from sklearn.preprocessing import MinMaxScaler 
scaler = MinMaxScaler() 
scaler.fit(train_data) 
scaled = scaler.fit_transform(train_data) 
scaled_df = pd.DataFrame(scaled, columns=train_data.columns)
scaled_df

index       MIP     STDIP      EKIP       SIP        MC      STDC  \
0    0.529365  0.000000  0.802795  0.661809  0.253572  0.718741  0.712888   
1    0.192321  0.000922  0.166968  0.881455  0.656239  0.253799  0.677285   
2    0.445189  0.002213  0.438080  0.663881  0.350318  0.055075  0.319970   
3    0.303987  0.008115  0.199171  0.977649  0.699805  0.274043  0.760801   
4    0.579234  0.008484  0.362938  0.945189  0.624382  0.205486  0.622194   
..        ...       ...       ...       ...       ...       ...       ...   
197  0.705782  0.999262  0.714726  0.115610  0.007214  0.024876  0.177340   
198  0.052880  0.999447  0.643673  0.116542  0.042078  0.013451  0.124374   
199  0.468306  0.999816  0.385265  0.157708  0.094046  0.010648  0.098001   
200  0.596558  1.000000  0.534339  0.090796  0.043697  0.022552  0.202238   
201  0.045212  1.000000  0.685928  0.086546  0.029069  0.027762  0.172382   

          EKC        SC  TARGET  
0    0.051019  0.001828     1.0  
1    0.110591  0.005268     1.0  
2    0.233974  0.040708     1.0  
3    0.107511  0.004454     1.0  
4    0.124351  0.007438     1.0  
..        ...       ...     ...  
197  0.305186  0.077418     0.0  
198  0.391268  0.132856     0.0  
199  0.448822  0.186732     0.0  
200  0.319009  0.079813     0.0  
201  0.291636  0.072299     0.0  

[202 rows x 10 columns]

In [23]:
scaled_df.mean()

index     0.467076
MIP       0.532453
STDIP     0.457439
EKIP      0.431036
SIP       0.262107
MC        0.139557
STDC      0.350877
EKC       0.287719
SC        0.113489
TARGET    0.500000
dtype: float64

In [24]:
X = pd.DataFrame(scaled_df.drop(['index', 'TARGET'], axis=1))
X

MIP     STDIP      EKIP       SIP        MC      STDC       EKC  \
0    0.000000  0.802795  0.661809  0.253572  0.718741  0.712888  0.051019   
1    0.000922  0.166968  0.881455  0.656239  0.253799  0.677285  0.110591   
2    0.002213  0.438080  0.663881  0.350318  0.055075  0.319970  0.233974   
3    0.008115  0.199171  0.977649  0.699805  0.274043  0.760801  0.107511   
4    0.008484  0.362938  0.945189  0.624382  0.205486  0.622194  0.124351   
..        ...       ...       ...       ...       ...       ...       ...   
197  0.999262  0.714726  0.115610  0.007214  0.024876  0.177340  0.305186   
198  0.999447  0.643673  0.116542  0.042078  0.013451  0.124374  0.391268   
199  0.999816  0.385265  0.157708  0.094046  0.010648  0.098001  0.448822   
200  1.000000  0.534339  0.090796  0.043697  0.022552  0.202238  0.319009   
201  1.000000  0.685928  0.086546  0.029069  0.027762  0.172382  0.291636   

           SC  
0    0.001828  
1    0.005268  
2    0.040708  
3    0.004454  
4    0.007438  
..        ...  
197  0.077418  
198  0.132856  
199  0.186732  
200  0.079813  
201  0.072299  

[202 rows x 8 columns]

In [25]:
y = pd.DataFrame(scaled_df['TARGET'])
y

TARGET
0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
..      ...
197     0.0
198     0.0
199     0.0
200     0.0
201     0.0

[202 rows x 1 columns]

In [26]:
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression(random_state=2019, solver='lbfgs').fit(X, y.values.ravel())

In [28]:
reg.predict_proba([[0.089, 0.122, 0.511, 0.237, 0.445, 0.513, 0.068, 0.857]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[0.10147268, 0.89852732]])

In [29]:
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors = 3, p = 2)

neigh.fit(X, y)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [31]:
import numpy as np

NewObject = np.array([0.089, 0.122, 0.511, 0.237, 0.445, 0.513, 0.068, 0.857])
neigh.predict([NewObject])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1.])

In [32]:
neigh.kneighbors([NewObject])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


(array([[0.91683252, 0.92621724, 0.9437487 ]]), array([[32, 87, 38]]))